import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('pageerror', e => errs.push('pageerror: ' + e.message));
p.on('console', m => { if (m.type() === 'error' && !m.text().includes('CERT')) errs.push('console: ' + m.text()); });
p.on('dialog', d => d.accept());
await p.goto('http://localhost:4173/');
await p.waitForTimeout(700);
await p.click('button:has-text("Code")');
await p.click('.mode-tabs button:has-text("Blocks + Text")');
await p.waitForTimeout(1500);
await p.click('.sim-btn'); await p.waitForTimeout(1500);
await p.screenshot({ path: '/tmp/claude-0/shots/blocks.png' });
console.log((await p.textContent('.editor-host')).slice(0, 300));
console.log(errs.join('\n') || 'no errors');
await b.close();
