import type { ComponentDef } from './types';
import { breadboardFull, breadboardSmall } from './defs/breadboard';
import { icSocket, perfboard, stripboard } from './defs/proto';
import { ceramicCapacitor, electrolyticCapacitor, photoresistor, potentiometer, resistor } from './defs/passive';
import { diode, led, rgbLed } from './defs/diodes';
import { npn, pnp, pushbutton, slideSwitch } from './defs/discrete';
import { battery } from './defs/power';
import { dcMotor, piezo } from './defs/output';
import { multimeter, oscilloscope } from './defs/instruments';
import { arduinoUno } from './defs/arduino';
import { esp32 } from './defs/esp32';
import { MORE_BOARDS } from './defs/boards2';
import { servo } from './defs/servo';
import { lcdI2C, lcdParallel } from './defs/lcd';
import { buildSpecParts } from '../parts';

export const DEFS: ComponentDef[] = [
  breadboardSmall, breadboardFull, perfboard, stripboard, icSocket,
  resistor, potentiometer, photoresistor, ceramicCapacitor, electrolyticCapacitor,
  led, rgbLed, diode,
  npn, pnp,
  pushbutton, slideSwitch,
  battery,
  dcMotor, piezo, servo,
  lcdParallel, lcdI2C,
  multimeter, oscilloscope,
  arduinoUno, esp32, ...MORE_BOARDS,
  ...buildSpecParts(),
];

const byType = new Map(DEFS.map((d) => [d.type, d]));

export function getDef(type: string): ComponentDef | undefined {
  return byType.get(type);
}

/** Add (or replace) a runtime-defined part, e.g. one generated by AI. */
export function registerDef(def: ComponentDef) {
  if (DEFS.some((d) => d.type === def.type)) throw new Error(`cannot replace built-in part ${def.type}`);
  byType.set(def.type, def);
}
